# Node network types: normal/internal
dev:
    logging: nil
    quiet: true
    default_port: 9999
    internal_ip: 0.0.0.0
    network_type: internal
prod:
    logging: nil
    quiet: true
    default_port: 9999
    internal_ip: 0.0.0.0
    network_type: normal
